
version: '3.8'

services:
  monero-suite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monero-suite
    environment:
      - NODE_ENV=production
    ports:
      # Web UI
      - "3000:3000"
      # Monero P2P (blockchain synchronization)
      - "18080:18080"
      # Monero RPC (interact with the daemon)
      - "18081:18081"
      # Monero ZMQ (event notifications)
      - "18082:18082"
      # Anonymous inbound port for I2P connections
      - "18085:18085"
      # Restricted RPC port for I2P
      - "18089:18089"
      # Tor SOCKS proxy
      - "9050:9050"
      # Tor control port
      - "9051:9051"
      # I2P HTTP proxy
      - "4444:4444"
      # I2P SOCKS proxy
      - "4447:4447"
      # I2P SAM port (for application connectivity)
      - "7656:7656"
      # I2P web console
      - "7070:7070"
    volumes:
      # Persistent blockchain data
      - ./data/monero/blockchain:/app/monero/blockchain
      # Log directories
      - ./data/monero/logs:/app/monero/logs
      - ./data/tor/logs:/app/tor/logs
      - ./data/i2p/logs:/app/i2p/logs
      # Tor data for persistent hidden services
      - ./data/tor/data:/app/tor/data
      - ./data/tor/hidden_service:/app/tor/hidden_service
      # I2P data directory
      - ./data/i2p/data:/app/i2p/data
      # Configuration files
      - ./data/monero/configs:/app/monero/configs
      - ./data/tor/config:/app/tor/config
      - ./data/i2p/config:/app/i2p/config
      # Optional: Mount custom binaries if available
      - ./data/monero/bin:/app/monero/bin
      - ./data/tor/bin:/app/tor/bin
      - ./data/i2p/bin:/app/i2p/bin
    restart: unless-stopped
    # This ensures logs are visible with docker-compose logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
